apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              image: nginx:1.18
              ports:
              - containerPort: 80
              resources:
                  requests:
                      cpu: 0.1
                      memory: 20M
                  limits:
                      cpu: 200m
                      memory: 20M
              livenessProbe:
                  httpGet:
                      path: /
                      port: 80
                  initialDelaySeconds: 15
                  periodSeconds: 30
              readinessProbe:
                  httpGet:
                      path: /
                      port: 80
                  periodSeconds: 5