apiVersion: apps/v1
kind: Deployment
metadata:
    name: java-todo
spec:
    replicas: 1
    selector:
        matchLabels:
            app: java-todo
    template:
        metadata:
            labels:
                app: java-todo
        spec:
            containers:
            - name: java-todo
              image: nachomillangarcia/java-insst:latest
              ports:
              - containerPort: 8080
              env:
              - name: DB_HOSTNAME
                value: service-mysql
              - name: DB_NAME
                value: todo
              - name: DB_USERNAME
                value: todo
              - name: DB_PASSWORD
                value: pass
              resources:
                  requests:
                      cpu: 0.3
                      memory: 0.5G
                  limits:
                      cpu: 0.5
                      memory: 1G
              livenessProbe:
                  tcpSocket:
                    port: 8080
                  initialDelaySeconds: 15
                  periodSeconds: 30
              readinessProbe:
                  tcpSocket:
                    port: 8080
                  periodSeconds: 5