apiVersion: v1
kind: Service
metadata:
  name: service-java-todo
spec:
  type: NodePort
  selector:
    app: java-todo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007